# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
# use_frameworks!

target 'WYOCNetwork_Example' do
  pod 'WYOCNetwork', :path => '../'

  target 'WYOCNetwork_Tests' do
    inherit! :search_paths

    
  end
end
